### ISSUE TITLE
AVX的tennis_sandy_bridge.dll

### ISSUE THREAD

**Issue by johnhollon** [seetafaceengine/SeetaFace6#26]
使用AVX指令CPU，会加载tennis_sandy_bridge.dll以支持AVX指令。在Intel Core I5 3320M上会抛出错误。

**Comment by johnhollon** [comment]
经切换计算动态库解决了问题。

**Comment by daguzt** [comment]
> 经切换计算动态库解决了问题。

请问一下应该怎么切换啊？
