### ISSUE TITLE
加载模型失败

### ISSUE THREAD

**Issue by philp123** [seetafaceengine/SeetaFace6#29]
A/libc: /usr/local/google/buildbot/src/android/ndk-release-r16/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type orz::Exception: open the model file:/sdcard/Android/data/jpgparser/face_detector.csta failed!" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 1984 (AsyncTask #1)

**Comment by liuchuan1122** [comment]
我也是在人脸检测加载模型出错了，你解决了吗？

**Comment by philp123** [comment]
> 我也是在人脸检测加载模型出错了，你解决了吗？

模型所在路径无读写权限，只需要在AndroidManifest.xml添加
