### ISSUE TITLE
后续是否会提供python或java接口？

### ISSUE THREAD

**Issue by fjibj** [seetafaceengine/SeetaFace6#3]

**Comment by seetafaceengine** [comment]
SeetaFace6 只维护了核心的 C++ 的接口，开发者在需要其他语言支持的时候，需要通过语言内置的方式进行扩展。 

这里给出不同语言的的扩展参考文件： 
《[Python 扩展C/C++](https://docs.python.org/zh-cn/3.8/extending/extending.html)》
《[Java 之JNI基础篇](https://blog.csdn.net/yingshukun/article/details/79053061?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task)》
《[Oracle Java Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/intro.html#programming_to_the_jni)》
《[C# 使用C++进行.NET编程](https://docs.microsoft.com/zh-cn/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=vs-2019)》
《[C# 从托管代码调用本机函数](https://docs.microsoft.com/zh-cn/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2019)》

特别指出，`Android`调用使用`java`开发，在对应的`SDK`打包中包含了`JNI`封装的代码，可以直接使用。其他平台的`JNI`封装也可以参考其实现。

后续开放要看开发版的用户和后续发展。而且多语言接口往往使用C++进行扩展的效率才最能够保证。
