### ISSUE TITLE
是否支持奔腾G3260

### ISSUE THREAD

**Issue by MiyamuraMiyako** [seetafaceengine/SeetaFace6#30]
执行V_SetModelPath报0xc000001d。似乎是指令集不支持。

**Comment by MiyamuraMiyako** [comment]
原来要重命名支持奔腾的dll

**Comment by daguzt** [comment]
> 原来要重命名支持奔腾的dll

请问应该怎么操作啊？只是将原来的tennis.dll删除再把tennis_pentium.dll重命名为tennis.dll就行了？我重命名也还是启动不了软件。。文档不是说所有dll丢进去部署就可以动态适应所有情况了吗。。是不是我还要有其他遗漏的地方啊，请教一下！

**Comment by MiyamuraMiyako** [comment]
@daguzt 主要看具体报什么错，跟我的错误一样吗？

**Comment by daguzt** [comment]
> @daguzt 主要看具体报什么错，跟我的错误一样吗？

我是用viewfaceCore那个项目的。软件打不开，然后事件查看器也是有一项错误也是DllNotFoundException，跟你在viewfaceCore的issues提的一模一样，还有其他报错 => 错误模块名称: KERNELBASE.dll，版本: 10.0.17763.292。就手头上的电脑，也是在新的机器上可以跑，比较旧的不行，测试的机器比较少，也没办法下定论。

**Comment by MiyamuraMiyako** [comment]
@daguzt 估计机器的CPU `太过于`老了

**Comment by daguzt** [comment]
> @daguzt 估计机器的CPU 太过于老了

可以解决吗？比如你说的重命名，seetaface文档不是说可以支持不同的指令集的吗。。这边也有奔腾的cpu，seetaface也有tennis_pentium.dll。。但是我重命名好像不行。。你是怎么解决啊呀？

**Comment by MiyamuraMiyako** [comment]
重命名不行就不好办了，先确定winerror是不是0xc000001d吧，是的就无解了，不是的话再根据问题查原因。

**Comment by daguzt** [comment]
> 重命名不行就不好办了，先确定winerror是不是0xc000001d吧，是的就无解了，不是的话再根据问题查原因。

好吧。。。感谢！！
