### ISSUE TITLE
证件照无法检测出来。

### ISSUE THREAD

**Issue by MiyamuraMiyako** [seetafaceengine/SeetaFace6#31]
Threshold 调整到 0.05，FaceSize 调整到 80才勉强检测出来部分证件照。

但是与摄像头检测出的人脸比对，相似度又极低。

**Comment by tjiasong** [comment]
你这确定？facesize 调整到20就可以比对出身份证上的照片了，最近模型 活体检测 初始化就异常😂

**Comment by MiyamuraMiyako** [comment]
@tjiasong 我这边把证件照放大一点就能识别了。

**Comment by daguzt** [comment]
> @tjiasong 我这边把证件照放大一点就能识别了。

我这边的证件照也是无法识别，请问这个放大一点具体是怎么样的实现的？怎么放大？还有你现在证件照与摄像头检测的人脸比对的相似度怎么样？

**Comment by MiyamuraMiyako** [comment]
@daguzt 长宽等比放大1.5倍；阈值要调低，0.27左右比较好（还要求比较好的环境光线）。

**Comment by MiyamuraMiyako** [comment]
@tjiasong 不是通过摄像头拍的证件照片，而是用阅读器读出来的。

**Comment by tjiasong** [comment]
本身就是读取身份证上的照片，身份证上的照片大小 102*126的。`this.cardEngine.SetProperty(SeetaFace.V6.SDK.Enums.DetectorProperty.PROPERTY_MIN_FACE_SIZE, 15);
				this.cardEngine.SetProperty(SeetaFace.V6.SDK.Enums.DetectorProperty.PROPERTY_THRESHOLD, threshold);`

**Comment by MiyamuraMiyako** [comment]
@tjiasong 看起来不是windows的库？

**Comment by tjiasong** [comment]
> @tjiasong 看起来不是windows的库？

实时上就是windows库，除了口罩识别初始化异常，其它都正常使用😂

**Comment by daguzt** [comment]
> @daguzt 长宽等比放大1.5倍；阈值要调低，0.27左右比较好（还要求比较好的环境光线）。

我这边facesize 20，阈值 0.9就能识别了，0.27误识别太可怕了。我是new一个证件照2倍长宽的bitmap，把证件照写在中间就行。。什么原理我不知道。。还有你能具体说一下相似度的问题吗？大量测试都很低吗？这样没法用的呀

**Comment by MiyamuraMiyako** [comment]
@daguzt 我10年前的照片跟我今年的照片还有我几个同事的照片都一样，相似度极低。。
