### ISSUE TITLE
开发包是否可直接免费商用

### ISSUE THREAD

**Issue by Tryljs** [seetafaceengine/SeetaFace6#5]
作者你好，seetaface6各平台开发包是否可直接免费商用？后续是否考虑开源？

**Comment by seetafaceengine** [comment]
可以免费商用。开源会考虑为后续安排。

**Comment by tianyunperfect** [comment]
请问readme里提到的模型是否可以商用？

> 可以免费商用。开源会考虑为后续安排。

**Comment by Tryljs** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
