### ISSUE TITLE
x64 GPU config not work

### ISSUE THREAD

**Issue by zhouyongxyz** [seetafaceengine/SeetaFace6#7]
terminate called after throwing an instance of 'ts::api::Exception'   what():  Compute device gpu has no memory device registered. Please call RegisterMemoryDevice firstly. Aborted (core dumped)

please enlighten me how to fix this problem.

**Comment by seetafaceengine** [comment]
Sorry, this open free SeetaFace6 prebuilt libraries do not support gpu computing.
